spring:
  application:
    name: shut-admin # 应用名称
  datasource:
    name: dataSource1 # 昵称
    type: com.alibaba.druid.pool.DruidDataSource # 连接池驱动
    druid: #druid相关配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/a-plan
      username: root
      password: 123456
      initial-size: 1 #配置初始化大小/最小/最大
      min-idle: 1
      max-active: 20
      max-wait: 60000 #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000 #间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 30000 #一个连接在池中最小生存的时间
      validation-query: SELECT 'x'  FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall #监控统计拦截的filters
      aop-patterns: com.aplan.mapper.* # mapper文件的包下
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true  # 是否启用statViewServlet配置
        url-pattern: "/druid/*"  # 访问监控页面
        reset-enable: false # 禁止手动重置监控数据
        login-username: admin # 设置监控页面的登陆名
        login-password: 12313 # 设置监控页面的登陆密码
        allow:
  redis:
    database: 10
    host: localhost
    port: 6379
    timeout: 5000s  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接
  thymeleaf: # 试图配置
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
web:
  upload-path: d:/data/ # 文件存储位置

knife4j: # swagger配置
  config:
    enable: true #是否开启swagger在线文档